# Site
repository: sproogen/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Umesh Kumar
title: WordPress Developer
email: umeshsingla05[AT]gmail.com
website: codechutney.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: kmr_umesh
github_username:  UmeshSingla

# Additional icon links
additional_links:
- title: WordPress StackExchange
  icon: fab fa-stack-exchange
  url: https://wordpress.stackexchange.com/users/32466/kumar

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello there, my name's Umesh Kumar and I work as a WordPress Developer. I'm mostly involved with Back-end development,or sometimes with front-end as well. I play well along in team and equally well as an individual contributor.

  I am most skilled in: <mark>WordPress [PHP, JS, CSS, APIs, Github, SVN]</mark> and have some experience working in bbPress [Migration].

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Incsub [ WPMU DEV/ CampusPress
        link: incsub.com
        sub_title: WordPress Developer
        caption: April 2014 - ongoing
        description: | # this will include new lines to allow paragraphs
          I've spent a majority of my development career here at Incsub so far, and it's been a great learning experience all along. I've worked on a variety of projects
          including the most famous WP Smush [I started when Yahoo api went away].
          I've been invloved in Plugin Development [ Development, Releases], Theme Development, API integration and bbPress migration.

      - layout: left
        title: rtCamp
        link: rtCamp.com
        sub_title: WordPress Developer
        caption: Februrary 2013 - March 2014
        description: | # this will include new lines to allow paragraphs
            My role at rtCamp mostly included working on client theme, internal projects along with learning being new to WordPress.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kurukshetra University
        caption: 2008 - 2012
        sub_title: B.Tech [Information Technology]
        description: | # this will include new lines to allow paragraphs
          During my time at college I started with LAN gaming - Counter Strike was first and then it was farming and building castle in Age of Empires and then came Dota 2. Our college hostel was fun and taught me great team work! I did attend lectures sometimes, also I did pass.
          In final years of my degree I worked on desktop application of our Training and Placement cell along with a small web application for Internet access management of the college students.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in programming some of my other interests and hobbies are:
      - Acryling Painting - It's a brand new hobby!!
      - Hiking/Camping, and I'm a bit into fitness.
      - Terrace Garden
      - Digital Nomading [Well, sometimes]
      - Cooking, ( only as a hobby ;))

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
