# Site
repository: sproogen/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Umesh Kumar
title: WordPress Developer
email: umeshsingla05[AT]gmail.com
website: codechutney.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: kmr_umesh
github_username:  UmeshSingla
wordpress_username:  Umeshsingla

# Additional icon links
additional_links:
- title: WordPress StackExchange
  icon: fab fa-stack-exchange
  url: https://wordpress.stackexchange.com/users/32466/kumar
- title: WordPress.org
  icon: fab fa-wordpress
  url: https://profiles.wordpress.org/Umeshsingla/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
google_analytics: "UA-34239627-1"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  Hello there, my name's Umesh Kumar and I'm currently working as a Plugin/Theme Back-end Developer at CampusPress/Incsub, LLC. My current role involves working on custom themes for Educational Institutions which includes handling of back-end as well as front-end development.
  
  
  I am more proficient in back-end development and have a decent experience working on front-end as well. I play well along in team as well as an individual contributor.
  

  I am most skilled in: <mark>WordPress [PHP, JS, CSS, API integration, Version Control: Git, SVN, Project Management]</mark> and have some experience working in bbPress as well [it mostly included a massive migration].
  Well versed with tools like JIRA, Bitbucket for managing projects and releases and a basic knowledge of system side of things. I've used Vagrant and Docker environment for local development.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Incsub
        link: incsub.com
        sub_title: Theme Developer [Campuspress]
        caption: May 2020 - ongoing
        description: | 
          As a Theme Developer my role includes:
            * Reviewing and Updating Plugin/Theme for our in-house network which hosts websites for Universities and Educational Institutions, 
            * Custom theme development using underscore based theme [CampusPress Flex](https://github.com/campuspress/campuspress-flex) as boiler plate.
          
          My job is to convert the Figma/XD designs to a beautiful mobile-first Website along with focus on accessibility. This includes but not limited to working on back-end such as custom Gutenberg blocks mainly using Advanced Custom Fields Plugin, API integrations, developing custom functionality, setting up Bitbucket Pipeline (CI/CD) for deployments.
          
          And a few times I take care of planning and delivery of the project along with handling weekly release on (CampusPress network)[https://campuspress.com/].
      - layout: left
        title: Incsub
        link: incsub.com
        sub_title: Plugin Developer [WPMU DEV]
        caption: April 2014 - May 2020
        description: | 
          I've spent a majority of my development career here at Incsub, and it's been a great learning experience all along. I've worked on a variety of projects
          including the popular [WP Smush Plugin](https://wordpress.org/plugins/wp-smushit/) along with it's API development using various image optimization libraries.

          As a part of DEV team I've actively worked on Plugin development which included adding new features, bug fixes and handling plugin releases along with handling support requests occasionally as a project owner.
          I started with working on MarketPress( A WooCommerce alternative, now retired ) bitcoin payment gateway integration, then helped with Pro Sites plugin. Further I took up Smush and worked on multiple major releases.
          
          One of the challenging project during the tenure was bbPress migration for WPMU DEV site forum. Having around 1.2 million posts with attachments along with additional functionality it was a challenging task ensuring lower downtime.

      - layout: left
        title: rtCamp
        link: rtCamp.com
        sub_title: WordPress Developer
        caption: Februrary 2013 - March 2014
        description: | 
            My role at rtCamp included working on client theme, internal projects mostly involving back-end development with some front-end work.
            I was a keen learner and contributor to WordPress core.

  - title: Education
    layout: list
    content:
      - layout: left
        title: BITS Pilani, India
        caption: 2021 - 2023
        sub_title: MS - WILP
        description: |
          I recently completed my Masters in Science. (WILP - Work Integrated Learning Program)

      - layout: left
        title: Kurukshetra University, India
        caption: 2008 - 2012
        sub_title: B.Tech
        description: |
          I completed my four years of technical education with Software development as main focus. During my time at college I was very much into LAN gaming - Counter Strike was first and then it was farming and building castle in Age of Empires, Dota 2. 
          
          Hostel was fun and taught me great team work!

          In 3rd and 4th year of my degree I worked on PHP Web application for our Training and Placement cell along with a small web application for Internet access management of the college students.
          The application designed for the Placement cell was in use for at least 3-4 years until when they finally got a better application to work with.:D 

  - title: Community Contribution
    layout: text
    content:
      I've been an active Community contributor in different ways. Be it Core Contribution, Organising Meetups/WordCamp, tried my skills as a Speaker. I enjoy helping people on [WordPress Stackexchange](https://wordpress.stackexchange.com/users/32466/kumar) and I find pride in owning these [badges on WordPress.org](https://profiles.wordpress.org/umeshsingla/#user-badges)

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in programming some of my other interests and hobbies are:
      - Acrylic Painting  - Fluid Art - It's a brand new hobby!!
      - Yoga, Meditation  - To be able to keep myself going. 
      - Hiking/Camping    - This seems to be a bit of past maybe:D, I haven't been to a hike for quite some time now.
      - Terrace Garden    - Love it, though I wish my terrace was a lot bigger to accommodate for more plants.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
